#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/miriambudayr/pet-project-90-go,github.com/stainless-sdks/pet-project-90-go"

go build -o terraform-provider-pet-project-90
