#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../pet-project-90-go
fi

echo "==> Linking with local directory"
go mod tidy -e
go mod edit -replace github.com/miriambudayr/pet-project-90-go="$LOCAL_GO"
